baseURL: https://averyan.ru
languageCode: ru
theme: stack
paginate: 5
title: AveryanAlex's blog

languages:
  ru:
    languageName: Русский
    weight: 1
  en:
    languageName: English
    weight: 2

DefaultContentLanguage: ru

permalinks:
  post: /p/:filename/
  page: /:filename/

params:
  mainSections:
    - post
  featuredImageField: image
  rssFullContent: true
  # favicon:

  footer:
    since: 2022
    # customText:

  dateFormat:
    published: Jan 02, 2006
    lastUpdated: Jan 02, 2006 15:04 MST

  sidebar:
      emoji: 🦜
    subtitle: Linux and physics fan.
    avatar:
      enabled: true
      local: true
      src: img/avatar.png

  article:
    math: false
    toc: true
    readingTime: false
    license:
      enabled: true
      default: Licensed under CC BY-NC-SA 4.0

  widgets:
    homepage:
      - type: search
      - type: archives
        params:
          limit: 5
      - type: categories
        params:
          limit: 10
      - type: tag-cloud
        params:
          limit: 10
    page:
      - type: toc

  opengraph:
    twitter:
      # site:
      card: summary_large_image

  # defaultImage:
  #   opengraph:
  #     enabled: false
  #     local: false
  #     src:

  colorScheme:
    toggle: true
    default: auto

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

menu:
  main: []

  social:
    - identifier: github
      name: GitHub
      url: https://github.com/averyanalex
      params:
        icon: brand-github

related:
  includeNewer: true
  threshold: 60
  toLower: false
  indices:
    - name: tags
      weight: 100

    - name: categories
      weight: 200

markup:
  # goldmark:
  #   renderer:
  #     ## Set to true if you have HTML content inside Markdown
  #     unsafe: false
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    tabWidth: 4
