clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

pipeline:
  build:
    image: klakegg/hugo
    commands:
      - hugo --minify
    when:
      event: [pull_request, push]
